- name: Install XAMPP
  hosts: all
  gather_facts: no
  tasks:
    # 1. Create Download Directory
    - name: Create download directory
      win_file:
        path: C:\Temp
        state: directory

    # 2. Download XAMPP
    - name: Download XAMPP 7.4.33 (64-bit)
      win_get_url:
        url: "https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.4.33/xampp-windows-x64-7.4.33-0-VC15-installer.exe"
        dest: "C:\\Temp\\xampp_installer.exe"
        force: yes

    # 3. Verify Download
    - name: Verify XAMPP download
      win_shell: |
        $file = Get-Item "C:\Temp\xampp_installer.exe"
        "File size: $($file.Length) bytes"
        "Last write time: $($file.LastWriteTime)"
        "File exists: $(Test-Path 'C:\Temp\xampp_installer.exe')"
      register: xampp_download_check

    - name: Display XAMPP download results
      debug:
        var: xampp_download_check.stdout_lines

    # 4. Install XAMPP silently with debug logging
    - name: Install XAMPP silently
      win_shell: |
        Start-Process -FilePath "C:\Temp\xampp_installer.exe" -ArgumentList "--mode unattended --debugtrace C:\Temp\xampp_install.log" -NoNewWindow -Wait
      register: xampp_install_output
      ignore_errors: yes

    # 5. Verify Installation
    - name: Verify XAMPP installation
      win_shell: if (Test-Path "C:\xampp\xampp-control.exe") { Write-Output "XAMPP installed successfully" } else { Write-Error "XAMPP installation failed" }
      register: xampp_install_result
      ignore_errors: yes

    # 6. Show Installation Result
    - name: Show XAMPP installation result
      debug:
        var: xampp_install_result.stdout

