---
- hosts: windows
  vars:
    temp_dir: C:\Temp
    sublime_url: https://download.sublimetext.com/Sublime%20Text%20Build%203211%20x64%20Setup.exe
    sublime_installer: "{{ temp_dir }}\\sublime_text_installer.exe"
    sublime_install_path: 
      - C:\Program Files\Sublime Text\sublime_text.exe
      - C:\Program Files (x86)\Sublime Text\sublime_text.exe
  tasks:
    - name: Create temp directory for installers
      win_file:
        path: "{{ temp_dir }}"
        state: directory

    - name: Download Sublime Text installer
      win_get_url:
        url: "{{ sublime_url }}"
        dest: "{{ sublime_installer }}"
        force: yes
        timeout: 300

    - name: Install Sublime Text
      win_command: "{{ sublime_installer }} /SILENT /NORESTART"
      register: install_result
      args:
        creates: "{{ sublime_install_path[0] }}"

    - name: Check Sublime Text installation paths
      win_stat:
        path: "{{ item }}"
      loop: "{{ sublime_install_path }}"
      register: sublime_paths

    - name: Display Sublime Text version
      debug:
        var: sublime_version.stdout_lines
      when: sublime_version is defined and sublime_version.rc == 0
